---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbbitmquser
data:
  default_user: rabbitmquser

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbbitmqpass
data:
  default_pass: DEBmbwkSrzy9D1T9cJfa            
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name:  rabbitmq-deploy
  labels:
    env: dev
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata: 
      name: rabbitmq-pod
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-con
          image: rabbitmq:3-management-alpine
          env:
            - name: RABBITMQ_CONFIG_FILE
              value: '/etc/pitstop/rabbitmq.conf' 
          volumeMounts: 
            - name: rabbitmq-user
              mountPath: /etc/pitstop/username
            - name: rabbitmq-pass
              mountPath: /etc/pitstop/password
            - name: rabbitmq-pvc 
              mountPath: /var/lib/rabbitmq
          ports: 
            - containerPort: 15672
            - containerPort: 5672
              protocol: TCP
      volumes: 
        - name: rabbitmq-user
          configMap: 
            name: rabbbitmquser
        - name: rabbitmq-pass 
          secret:
            secretName: rabbbitmqpass  
            
        - name: rabbitmq-pvc    
          persistentVolumeClaim:
            claimName: rabbitmq-pvc

